# Generated by Django 3.2.12 on 2022-04-16 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('APP', 'Logs from app'), ('BOX', 'Logs from box'), ('WEBLogs from web', 'Web'), ('MAN', 'Manual logs'), ('NON', 'No given source')], default='NON', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
                'db_table': 'log',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
