name: Mobile CI

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
  pull_request:
    paths:
      - 'washee_app/**'

jobs:
  build:
    runs-on: macos-latest
    steps:
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', or 'stable' default to: 'stable'
        flutter-version: '2.10.5' # set to the flutter version of MartinBruun due to previous errors
    
    - name: Setup necessary environment files
      working-directory: ./washee_app
      run: |
        echo "WEB_API_HOST=http://localhost:8000" > .env.dev
        echo "BOX_API_HOST=http://localhost:8001" >> .env.dev
        echo "BOX_WIFI_SSID=boxNetworkName" >> .env.dev
        echo "BOX_WIFI_PASSWORD=boxNetworkPassword" >> .env.dev
        echo "BOX_HAS_INTERNET=true" >> .env.dev
        echo "Necessary production environment to satisfy flutter assets" > .env.prod

    - name: Lint according to analysis_options.yaml rules
      working-directory: ./washee_app
      run: |
        flutter analyze

    - name: Run flutter tests and check for minimum coverage afterwards
      working-directory: ./washee_app
      run: |
        flutter pub get
        flutter test --coverage

    - uses: VGVentures/very-good-coverage@v1.1.1
      with:
        path: "./washee_app/coverage/lcov.info"
        min_coverage: 13
        exclude: "**/*_observer.dart **/change.dart"

    - name: Start an Android Emulator and Run Integration Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        profile: pixel
        script: |
          cd washee_app
          flutter drive --target=test_driver/app.dart
          flutter test integration_test
          cd ..

      
    





