name: Web CI

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
  pull_request:
    paths:
      - 'washee_web/**'

env:
  MIN_COVERAGE: 75

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check for linting before running tests
      uses: py-actions/flake8@v2
      with:
          path: "washee_web"
          max-line-length: 9000

    - name: Run Tests
      working-directory: ./washee_web
      run: |
        docker-compose exec -T web pytest --cov=. --cov-fail-under=$MIN_COVERAGE
