# Generated by Django 3.2.12 on 2022-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
    ]
