Highest Priority:
    - '(urgent|critical|fix|bug|flaw)'
Must have:
    - '(must|Must)'
Should have:
    - '(should|Should)'
Could have:
    - '(could|Could)'
Won't have:
    - '(wont|Wont)'
Need documentation:
    - '(*)'
Need grooming:
    - '(*)'
