version: '3.8'

services:
  web:
    build: ./washee_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./washee_web/:/usr/src/washee_web/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    environment:
      - POSTGRES_DB=$${DB_NAME}
      - POSTGRES_USER=$${DB_USER}
      - POSTGRES_PASSWORD=$${DB_PASSWORD}
    ports:
      - 5432:5432
volumes:
  postgres_data: