version: '3.8'

services:
  web:
    build:
      context: ./washee_web
      dockerfile: Dockerfile.prod
    command: gunicorn washee_web.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/washee_web/web/staticfiles
      - media_volume:/home/washee_web/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod.web
    depends_on:
      - db
    links:
      - db:db
  db:
    build: ./washee_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    ports:
      - 65432:5432
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/washee_web/web/staticfiles
      - media_volume:/home/washee_web/web/mediafiles
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

volumes:
  postgres_data:
  static_volume:
  media_volume:
