version: '3.8'

services:
  web:
    build: ./washee_web
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - ./washee_web/:/usr/src/washee_web/
    ports:
      - "${DJANGO_HOST_PORT}:${DJANGO_PORT}"
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db
  db:
    build: ./washee_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "${DB_HOST_PORT}:${DB_PORT}"
  box:
    build: ./washee_box
    volumes:
      - ./washee_box/:/usr/src/washee_box/
    env_file:
      - ./.env
    ports:
      - "${BOX_HOST_PORT}:${BOX_PORT}"
  #NOT POSSIBLE, nor necessary, at the moment.
  #app:
  #  build: ./washee_app
  #  command: flutter run web-server --web-port ????
  #  volumes:
  #    - ./washee_app/:/usr/src/washee_app/
  #  ports:
  #    - ????:????
  #  env_file:
  #    - ./.env
volumes:
  postgres_data: