version: '3.8'

services:
  web:
    build: ./washee_web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./washee_web/:/usr/src/washee_web/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    links:
      - db:db
  db:
    build: ./washee_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 65432:5432
  box:
    build: ./washee_box
    command: python washee_box_entry.py
    volumes:
      - ./washee_box/:/usr/src/washee_box/
    env_file:
      - ./.env.dev
    ports:
      - "8001:5000"
volumes:
  postgres_data: