# Generated by Django 3.2.12 on 2022-05-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricityblock',
            name='green_score',
            field=models.IntegerField(default=-1),
        ),
    ]
