# Generated by Django 3.2.12 on 2022-04-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
