// Mocks generated by Mockito 5.0.17 from annotations
// in washee/test/features/get_machines/get_machines_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:washee/core/helpers/box_communicator.dart' as _i2;
import 'package:washee/core/washee_box/machine_model.dart' as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [BoxCommunicator].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunicator extends _i1.Mock implements _i2.BoxCommunicator {
  @override
  String get lockURL =>
      (super.noSuchMethod(Invocation.getter(#lockURL), returnValue: '')
          as String);
  @override
  String get unlockURL =>
      (super.noSuchMethod(Invocation.getter(#unlockURL), returnValue: '')
          as String);
  @override
  String get getMachinesURL =>
      (super.noSuchMethod(Invocation.getter(#getMachinesURL), returnValue: '')
          as String);
  @override
  _i3.Future<Map<String, dynamic>> getMachines() => (super.noSuchMethod(
          Invocation.method(#getMachines, []),
          returnValue: Future<Map<String, dynamic>>.value(<String, dynamic>{}))
      as _i3.Future<Map<String, dynamic>>);
  @override
  _i3.Future<Map<String, dynamic>> lockOrUnlock(
          String? command, _i4.MachineModel? machine, Duration? duration) =>
      (super.noSuchMethod(
              Invocation.method(#lockOrUnlock, [command, machine, duration]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
}
