// Mocks generated by Mockito 5.0.17 from annotations
// in washee/test/features/unlock/data/repositories/unlock_repo_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:washee/core/network/network_info.dart' as _i3;
import 'package:washee/core/washee_box/machine_model.dart' as _i6;
import 'package:washee/features/unlock/data/datasources/unlock_remote.dart'
    as _i5;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResponse_0<T> extends _i1.Fake implements _i2.Response<T> {}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i3.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
}

/// A class which mocks [UnlockRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemote extends _i1.Mock implements _i5.UnlockRemote {
  @override
  _i4.Future<_i2.Response<dynamic>> unlock(
          _i6.MachineModel? machine, Duration? duration) =>
      (super.noSuchMethod(Invocation.method(#unlock, [machine, duration]),
              returnValue: Future<_i2.Response<dynamic>>.value(
                  _FakeResponse_0<dynamic>()))
          as _i4.Future<_i2.Response<dynamic>>);
}
