// Mocks generated by Mockito 5.0.17 from annotations
// in washee/test/features/unlock/data/repositories/unlock_repo_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:washee/core/network/network_info.dart' as _i2;
import 'package:washee/core/washee_box/machine_model.dart' as _i5;
import 'package:washee/features/unlock/data/datasources/unlock_remote.dart'
    as _i4;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i2.NetworkInfo {
  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}

/// A class which mocks [UnlockRemote].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemote extends _i1.Mock implements _i4.UnlockRemote {
  @override
  _i3.Future<Map<String, dynamic>> unlock(
          _i5.MachineModel? machine, Duration? duration) =>
      (super.noSuchMethod(Invocation.method(#unlock, [machine, duration]),
              returnValue:
                  Future<Map<String, dynamic>>.value(<String, dynamic>{}))
          as _i3.Future<Map<String, dynamic>>);
}
