name: App Confidence

# App confidence continious integration testing
# Confidence testing are for getting quick feedback

on:
  pull_request:
    paths:
      - 'washee_app/**'
  workflow_run:
    workflows: [Setup]
    types:
      - completed

env:
  MIN_COVERAGE: "Last set to 13, but don't know how to inject as environment variable"

jobs:
  app_confidence:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    # SETUP
    - uses: ./.github/workflows/setup.yml

    # TESTING

    - name: Lint according to analysis_options.yaml rules
      working-directory: ./washee_app
      run: |
        flutter analyze

    - name: Run flutter tests and check for minimum coverage afterwards
      working-directory: ./washee_app
      run: |
        flutter pub get
        flutter test --coverage

    - uses: VGVentures/very-good-coverage@v1.1.1
      with:
        path: "./washee_app/coverage/lcov.info"
        min_coverage: 13
        exclude: "**/*_observer.dart **/change.dart"