name: Assurance

# General assurance continious delivery testing
# Assurance testing are slow end-to-end, acceptance, performance, security, etc. tests

on:
  pull_request:
  workflow_run:
    workflows: [App Confidence, Box Confidence, Web Confidence]
    types:
      - completed

jobs:
  assurance:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    # SETUP
    - uses: actions/checkout@v2

    # SHOULD be a production looking build it starts up instead!
    - name: Startup all containers
      run: |
        docker-compose up -d --build

    # TESTING

    # THIS IS NOT WORKING as of now!
    #- name: Start an Android Emulator and Run App Integration Tests
    #  uses: reactivecircus/android-emulator-runner@v2
    #  with:
    #    api-level: 29
    #    profile: pixel
    #    script: ./scripts/app/integration_test.sh

    # NEEDS a renaming of "integration test" to "assurance test" for app
    # NEEDS Web Assurance test setup
    # NEEDS Box Assurance test setup
    # Shell scripts called "assurance_test" should hold all the logic for assuring the outcome is in a releaseable state
    # (Releaseable state => the branch can be the new production release in under 5 seconds)

    # SHOULD be a production looking build it tears down instead!
    - name: Finish testing and Clean Up
      run: |
        docker-compose down -v

    - name: Fail Assurance, given it is not yet setup properly
      run: exit 1