name: Box CI

on:
  pull_request:
    paths:
      - "washee_box/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build, run, test and tear down
        run: |
          docker-compose up -d --build box
          docker-compose down -v
