name: Box CI

on:
  pull_request:
    paths:
      - 'washee_box/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Move into correct folder
      run: |
        docker-compose build
        docker-compose run -d box
        docker-compose exec -T box pytest       
        docker-compose down -v
