name: Box CI

on:
  pull_request:
    paths:
      - "washee_box/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check for linting before running tests
        uses: py-actions/flake8@v2
        with:
          path: "washee_box"
          max-line-length: 9000

      - name: Build, run, test and tear down
        run: |
          docker-compose up -d --build box
          docker-compose exec -T box python3 -m pytest --cov=. --cov-fail-under=42
          docker-compose down -v
