name: Docker Image CI

on:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image (previously used this syntax after P6 :$(date +%s) )
      run: docker build . --file Dockerfile --tag p6
    - name: Run tests (Setup as python test now)
      run: docker run p6 sh -c "python -m pytest -vv"
