name: "Set Issue Label, Assignee, Project and Pre-Fix"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: '[{"keywords": ["*"], "labels": ["Need documentation", "Need grooming", "0: Suggestion"], "assignees": ["username"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
