name: "Set Issue Label, Assignee, Project and Pre-Fix"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "title"
          parameters: '[{"keywords": ["0:"], "labels": ["Need documentation", "Need grooming", "0: Suggestion"], "assignees": ["MartinBruun"]},{"keywords": ["1:"], "labels": ["Need documentation", "Need grooming", "1: Must have"], "assignees": ["MartinBruun"]},{"keywords": ["2:"], "labels": ["Need documentation", "Need grooming", "2: Should have"], "assignees": ["MartinBruun"]},{"keywords": ["3:"], "labels": ["Need documentation", "Need grooming", "3: Could have"], "assignees": ["MartinBruun"]},{"keywords": ["4:"], "labels": ["Need documentation", "Need grooming", "4: Wont have"], "assignees": ["MartinBruun"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
