name: Label PRs 

on:
  pull_request:
    types: [synchronize, opened, reopened, edited, closed]

env:
  BASE_BRANCH: ${{ github.base_ref }}

jobs:
  add-fix-label:
    runs-on: ubuntu-latest
    steps:
      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        if: BRANCH HAS A LINKED ISSUE
        with:
          github_token: ${{ github.token }}
          labels: Fix

  add-increment-label:
    runs-on: ubuntu-latest
    steps:
      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        if: BRANCH DOES NOT HAVE FIX LABEL
        with:
          github_token: ${{ github.token }}
          labels: Increment

  remove-increment-label:
    runs-on: ubuntu-latest
    steps:
      - name: remove labels
        uses: actions-ecosystem/action-remove-labels@v1
        if: BRANCH HAS A LINKED ISSUE
        with:
          github_token: ${{ github.token }}
          labels: Increment