name: Mobile CI

on:
  pull_request:
    paths:
      - 'mobile_app/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Move into correct folder
      run: cd mobile_app
    - name: Build Mobile App
      run: 
    - name: Run tests
      run: 
