name: Web CI

on:
  pull_request:
    paths:
      - 'washee_web/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run linter before running tests
      uses: py-actions/flake8@v2
    - name: Build, run, test and tear down
      working-directory: ./washee_web
      run: |
        chmod +x entrypoint.sh
        docker-compose up -d --build web
        docker-compose exec -T web pytest
        docker-compose down -v
