name: Web CI

on:
  pull_request:
    paths:
      - 'washee_web/**'

env:
  MIN_COVERAGE: 75

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check for linting before running tests
      uses: py-actions/flake8@v2
      with:
          path: "washee_web"
          max-line-length: 9000

    - name: Build, run, test and tear down
      working-directory: ./washee_web
      run: |
        chmod +x entrypoint.sh
        docker-compose up -d --build web
        docker-compose exec -T web pytest --cov=. --cov-fail-under=$MIN_COVERAGE
        docker-compose down -v
