name: Web CI

on:
  pull_request:
    paths:
      - 'washee_web/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup, build, test and tear down containers
      working-directory: ./washee_web
      run: |
        chmod +x app/entrypoint.sh
        docker-compose up -d --build
        docker-compose exec -T web pytest
        docker-compose down -v
